# Generated by Django 4.2.2 on 2023-06-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0003_remove_trait_pet'),
        ('pets', '0002_alter_pet_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='traits',
            field=models.ManyToManyField(related_name='traits', to='traits.trait'),
        ),
    ]
